# Generated by Django 6.0 on 2025-12-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='vendor_docs/address/'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='vendor_docs/license/'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='vendor_docs/gst/'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='vendor_docs/id/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='operating_areas',
            field=models.TextField(blank=True, help_text='Comma separated list of cities'),
        ),
    ]
