# Generated by Django 6.0 on 2025-12-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pickuprequest'),
        ('app', '0002_user_address_proof_user_business_license_and_more'),
    ]

    operations = [
    ]
