# Generated by Django 5.2.9 on 2026-01-05 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_merge_20251230_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity in Kg', max_digits=10),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='scrap_type',
            field=models.CharField(default='Mixed', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='vendor_id_proof',
            field=models.FileField(blank=True, null=True, upload_to='vendor_docs/id/'),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='client_docs/id/'),
        ),
    ]
